name: GitHub Actions
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Realiza checkout
        uses: actions/checkout@v4.1.2
          
      - name: Configura ambiente
        uses: actions/setup-dotnet@v1
        with: 
          dotnet-version: '6.0.x'

      - name: Restaura dependências
        run: dotnet restore MockAPI/MockAPI.sln

      - name: Builda o projeto
        run: dotnet build MockAPI/MockAPI.sln
          
      - name: Realiza testes automatizados
        run: |
          dotnet test Tests/Tests.csproj
          test_result=$?
          if [ $test_result -ne 0 ]; then
            echo "Testes falharam."
            exit 1
          else
            echo "Testes passaram com sucesso."
          fi
