name: GitHub Actions
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Realiza checkout
        uses: actions/checkout@v4.1.2
          
      - name: Configura ambiente
        uses: actions/setup-dotnet@v1
        with: 
          dotnet-version: '6.0.x'

      - name: Restaura as dependências
        run: dotnet restore MockAPI/MockAPI.sln

      - name: Builda o projeto
        run: dotnet build MockAPI/MockAPI.sln

      - name: Roda a API
        run: |
          dotnet run --project MockAPI/MockAPI.csproj &
          dotnet test Tests/Tests.csproj &
          pkill -f "dotnet run --project MockAPI/MockAPI.csproj"
          
      - name: Verifica resultados dos testes
        run: |
          test_result=$(dotnet test Tests/Tests.csproj | grep "Failed:")
          if [[ -n "$test_result" ]]; then
            echo "Testes falharam."
            exit 1
          else
            echo "Testes realizados com sucesso."
          fi
