name: GitHub Actions
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Realiza checkout
        uses: actions/checkout@v4.1.2
          
      - name: Configura ambiente
        uses: actions/setup-dotnet@v1
        with: 
          dotnet-version: '6.0.x'

      - name: Restaura as dependências e builda o projeto
        run: |
          dotnet restore MockAPI/MockAPI.sln
          dotnet build MockAPI/MockAPI.sln

      - name: Roda os testes
        run: dotnet test Tests/Tests.csproj --no-build

      - name: Roda a API
        run: |
          dotnet run --project MockAPI/MockAPI.csproj &
          pkill -f "dotnet run --project MockAPI/MockAPI.csproj"
