name: GitHub Actions
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Realiza checkout
        uses: actions/checkout@v4.1.2
          
      - name: Configura ambiente
        uses: actions/setup-dotnet@v1
        with: 
          dotnet-version: '8.0.x'

      - name: Restaura as dependências
        run: dotnet restore MockAPI/MockAPI.sln

      - name: Builda o projeto
        run: dotnet build MockAPI/MockAPI.sln

      - name: Roda a API
        run: dotnet run MockAPI.sln

      - name: Executa testes de integração
        run: dotnet test
